version: '3.3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:13
    volumes:
      - ticket_assignment_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ticket_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A chat worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0

volumes:
  ticket_assignment_db_data:
    driver: local
