# Generated by Django 5.0.4 on 2024-09-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_agent_language_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
